services:
#    artesanik.syliusextendedcheckoutplugin.example:
#        class:     Artesanik\SyliusExtendedCheckoutPlugin\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
  artesanik_sylius_extended_checkout_plugin.form.extension.address.type:
    class: Artesanik\SyliusExtendedCheckoutPlugin\Form\Extension\AddressTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType }