# Delete these routes and define your own shop routes here

artesanik_sylius_extended_checkout_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: ArtesanikSyliusExtendedCheckoutPlugin:Greeting:staticallyGreet
        name: ~

artesanik_sylius_extended_checkout_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: ArtesanikSyliusExtendedCheckoutPlugin:Greeting:dynamicallyGreet
        name: ~
